networks:
  app-network:
    driver: bridge

volumes:
  postgresql-data:

services:
  ## Database ##
  postgresql:
    image: postgres:15
    container_name: postgresql-db
    hostname: postgresql
    environment:
      POSTGRES_USER: user # change!
      POSTGRES_PASSWORD: password # change!
      POSTGRES_DB: dojo_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always

  ## Backend ##
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SERVICE_NAME: backend
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgresql:5432/dojo_db'
      DB_DRIVER_CLASS: org.postgresql.Driver
      CORS_ORIGIN: '*'
      CORS_WEBSOCKET_ALLOWED_HOST: '*'
      CORS_METHODS: 'GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD'
      TZ: America/Sao_Paulo
    depends_on:
      - postgresql
    networks:
      - app-network
    restart: always

  ## Frontend ##
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
